### ISSUE TITLE
This authorization code has been used

### ISSUE THREAD

**Issue by menan** [mmangino/mogli#128]
I keep getting this exception for only last couple days. What do you think it could be?

Mogli::Client::OAuthException (This authorization code has been used.)

**Comment by mmangino** [comment]
A stacktrace would be helpful. It sounds like an authorization code is being used multiple times. Make sure you exchange the code for a token once and then store the token.

**Comment by menan** [comment]
It's happening every time I call the current_facebook_user object. I am not storing any session variables manually. Should I?

BTW: I am using facebooker2. I guess I am suppose to post this in there. I just noticed it, My bad.

Here is my stack trace, there is not a lot:

```
app/controllers/application_controller.rb:31:in `current_user'
app/controllers/songs_controller.rb:18:in `index'

```

Here is my current_user method:

```
  def current_user
    @me = User.find_by_facebook_id(current_facebook_user.id) if current_facebook_user
  end
```

Thank you

**Comment by mmangino** [comment]
That seems awfully incomplete, since the call should be somewhere inside current_facebook_user. Basically, once you use a code, you need to cache the token info and inflate the session yourself.

**Comment by menan** [comment]
current_facebook_user is implemented under facebooker2. So, I am not sure how that works. I will take a look. However it looks like an issue with Facebook. Other users are facing similar issues too. According to their december update or something.

**Comment by mmangino** [comment]
It is implemented under facebooker, but getting that stacktrace is still helpful.

Mike

**Comment by menan** [comment]
Sorry bro, I am pretty new to rails haha. I thought that was the stack trace. Here is where things are going wrong in facebooker.

```
/Users/alexandrecarriere/.bundler/ruby/1.8/mogli-b8f68b5d7e44/lib/mogli/client.rb:79:in `raise_error_by_type_and_message'
/Users/alexandrecarriere/.bundler/ruby/1.8/mogli-b8f68b5d7e44/lib/mogli/client.rb:70:in `raise_client_exception'
/Users/alexandrecarriere/.bundler/ruby/1.8/mogli-b8f68b5d7e44/lib/mogli/client.rb:52:in `create_from_code_and_authenticator'
/Users/alexandrecarriere/.bundler/ruby/1.8/facebooker2-504cc261af61/lib/facebooker2/rails/controller.rb:231:in `oauth2_fetch_client_and_user_from_cookie'
/Users/alexandrecarriere/.bundler/ruby/1.8/facebooker2-504cc261af61/lib/facebooker2/rails/controller.rb:221:in `oauth2_fetch_client_and_user'
/Users/alexandrecarriere/.bundler/ruby/1.8/facebooker2-504cc261af61/lib/facebooker2/rails/controller.rb:16:in `current_facebook_user'
app/controllers/application_controller.rb:31:in `current_user'
app/controllers/users_controller.rb:28:in `show'

```

**Comment by mmangino** [comment]
This means you are using the code passed in from Facebook  multiple times. What I've done is to instead have a special URL that the oauth code sends the login to. In there, I get the client information using the following code:

```
mogli_client = Mogli::Client.create_from_code_and_authenticator(params[:code], authenticator)
facebook_user = Mogli::User.find("me", mogli_client)
session[:facebook_access_token] = mogli_client.access_token
session[:facebook_user_id] = facebook_user.id
```

The rest of our application then looks for the access token and the user id and uses them to create the facebook user and session.

Mike

**Comment by menan** [comment]
I've got it to work with the custom current_facebook_user method using the session token like you said. You might want to fix the facebooker though. It seems broken. Thanks for your help.

**Comment by mmangino** [comment]
I don't do anything with Facebook anymore, so I'd rather somebody who has a real world test case to send a patch.

Mike

**Comment by menan** [comment]
Sounds good :) I am not smart enough to fix your code man sorry.
